# THIS FILE CACHES /ask AND /ask-agent ANSWERS.
#
# Two tiers, cheapest first:
#   1. Redis, exact match - the SAME question asked twice (after trim/
#      lowercase) returns in milliseconds, no Elasticsearch or Ollama call
#      at all.
#   2. Elasticsearch, semantic match - a REWORDED version of a question
#      already answered before. Costs one embedding call to check, but
#      still skips the expensive part: hybrid search + LLM generation.
#
# A miss on both falls through to a full recompute, and every fresh answer
# gets written to both tiers so future repeats AND future rewordings hit
# sooner.
#
# Both tiers key on endpoint (ask vs ask-agent give different answers for
# the same question) and CHAT_MODEL (so switching models, like the
# llama3.2 -> qwen2.5:7b swap in Phase 2, can't serve a stale answer that
# was actually generated by a different model).

import hashlib
import json
import logging
from datetime import datetime, timezone

import redis
from elasticsearch import Elasticsearch

from . import config_ph1 as config
from .embeddings_ph1 import embed_text
from .es_client_ph1 import get_client as get_es_client

logger = logging.getLogger("sentinelcopilot")

CACHE_INDEX_MAPPING = {
    "mappings": {
        "properties": {
            "question": {"type": "text"},
            "embedding": {
                "type": "dense_vector",
                "dims": config.EMBED_DIMS,
                "index": True,
                "similarity": "cosine",
            },
            "endpoint": {"type": "keyword"},
            "model": {"type": "keyword"},
            "result": {"type": "text", "index": False},
            "created_at": {"type": "date"},
        }
    }
}


def get_client() -> redis.Redis:
    return redis.Redis.from_url(config.REDIS_URL, decode_responses=True)


def ensure_cache_index(es: Elasticsearch) -> None:
    """Creates the semantic-cache index if it doesn't exist yet. Called once
    at app startup (see main_ph1.py) - safe to call every boot, it's a
    no-op once the index is there."""
    if not es.indices.exists(index=config.ES_CACHE_INDEX):
        es.indices.create(index=config.ES_CACHE_INDEX, body=CACHE_INDEX_MAPPING)


def _cache_key(endpoint: str, question: str) -> str:
    normalized = question.strip().lower()
    digest = hashlib.sha256(
        f"{endpoint}:{config.CHAT_MODEL}:{normalized}".encode("utf-8")
    ).hexdigest()
    return f"sentinelcopilot:{endpoint}:{digest}"


def _semantic_lookup(endpoint: str, question: str) -> dict | None:
    """Embeds the question and searches ES_CACHE_INDEX for the closest PAST
    question cached for this endpoint+model. Returns its answer if the
    match scores at or above SEMANTIC_CACHE_SCORE_THRESHOLD, else None -
    same degrade-to-None contract as the exact-match path, including on any
    Elasticsearch/Ollama error, so a semantic-cache outage never breaks
    /ask or /ask-agent."""
    try:
        vector = embed_text(question)
        resp = get_es_client().search(
            index=config.ES_CACHE_INDEX,
            knn={
                "field": "embedding",
                "query_vector": vector,
                "k": 1,
                "num_candidates": 50,
                "filter": {
                    "bool": {
                        "must": [
                            {"term": {"endpoint": endpoint}},
                            {"term": {"model": config.CHAT_MODEL}},
                        ]
                    }
                },
            },
            size=1,
        )
    except Exception:
        return None

    hits = resp["hits"]["hits"]
    if not hits or hits[0]["_score"] < config.SEMANTIC_CACHE_SCORE_THRESHOLD:
        return None

    logger.info(
        "semantic cache hit: %r ~= %r (score=%.4f)",
        question,
        hits[0]["_source"]["question"],
        hits[0]["_score"],
    )
    return json.loads(hits[0]["_source"]["result"])


def get_cached_answer(client: redis.Redis, endpoint: str, question: str) -> dict | None:
    """Returns the cached result dict, or None on a miss on BOTH tiers -
    including when Redis or Elasticsearch is unreachable, so a cache outage
    degrades to "always recompute" instead of taking the whole API down."""
    try:
        raw = client.get(_cache_key(endpoint, question))
        if raw:
            return json.loads(raw)
    except redis.RedisError:
        pass

    return _semantic_lookup(endpoint, question)


def set_cached_answer(client: redis.Redis, endpoint: str, question: str, result: dict) -> None:
    try:
        client.setex(
            _cache_key(endpoint, question),
            config.CACHE_TTL_SECONDS,
            json.dumps(result),
        )
    except redis.RedisError:
        pass

    try:
        get_es_client().index(
            index=config.ES_CACHE_INDEX,
            document={
                "question": question,
                "embedding": embed_text(question),
                "endpoint": endpoint,
                "model": config.CHAT_MODEL,
                "result": json.dumps(result),
                "created_at": datetime.now(timezone.utc).isoformat(),
            },
        )
    except Exception:
        pass
