# THIS FILE CACHES /ask AND /ask-agent ANSWERS IN REDIS.
#
# Same question asked twice currently means two full round trips through
# Elasticsearch (hybrid search) and Ollama (embedding + generation) - the
# expensive part of every request. Redis lets a repeat question skip all of
# that and return in milliseconds instead.
#
# Cache key includes the endpoint (ask vs ask-agent give different answers
# for the same question) and CHAT_MODEL (so switching models, like the
# llama3.2 -> qwen2.5:7b swap in Phase 2, can't serve a stale answer that
# was actually generated by a different model).

import hashlib
import json

import redis

from . import config_ph1 as config


def get_client() -> redis.Redis:
    return redis.Redis.from_url(config.REDIS_URL, decode_responses=True)


def _cache_key(endpoint: str, question: str) -> str:
    normalized = question.strip().lower()
    digest = hashlib.sha256(
        f"{endpoint}:{config.CHAT_MODEL}:{normalized}".encode("utf-8")
    ).hexdigest()
    return f"sentinelcopilot:{endpoint}:{digest}"


def get_cached_answer(client: redis.Redis, endpoint: str, question: str) -> dict | None:
    """Returns the cached result dict, or None on a miss - including when
    Redis itself is unreachable, so a cache outage degrades to "always
    recompute" instead of taking the whole API down."""
    try:
        raw = client.get(_cache_key(endpoint, question))
    except redis.RedisError:
        return None
    return json.loads(raw) if raw else None


def set_cached_answer(client: redis.Redis, endpoint: str, question: str, result: dict) -> None:
    try:
        client.setex(
            _cache_key(endpoint, question),
            config.CACHE_TTL_SECONDS,
            json.dumps(result),
        )
    except redis.RedisError:
        pass
